const obj = [
  {
    id: "1",
    name: "Apple M1 Mackbook",
    website: "Amazon",
    currentPrice: "800",
    rating: "4.9",
    img: "",
  },
  {
    id: "2",
    name: "Apple Watch Series.",
    website: "Flipkart",
    currentPrice: "800",
    rating: "4.7",
    img: "",
  },
  {
    id: "3",
    name: "Iphone 15 Pro Max",
    website: "Myntra",
    currentPrice: "800",
    rating: "4.6",
    img: "",
  },
  {
    id: "4",
    name: "Apple Airtag",
    website: "Apple.com",
    currentPrice: "800",
    rating: "4.8",
    img: "",
  },
  {
    id: "5",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "6",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "7",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "8",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "9",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "9",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "9",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  },
  {
    id: "9",
    name: "Samsung Z-Flip 4",
    website: "Amazon",
    currentPrice: "600",
    rating: "4.7",
    img: "",
  }
];

export function getFakeProducts() {
  return obj;
}
